<?php
$site = [
    'name' => 'AHS Dental Clinic',
    'short_name' => 'AHS',
    'tagline' => 'Thoughtful care for lasting smiles',
    'phone' => '+92 (300) 8810227',
    'phone_href' => 'tel:+923008810227',
    'email' => 'hello@ahsdentalclinic.com',
    'address' => 'H-R1, Lucky Street Tajnagh Housing Scheme',
    'city' => 'Lahore',
    'hours' => 'Mon–Fri 8:00–6:00 · Sat 9:00–2:00',
    'hours_short' => 'Mon–Sat, 8am–6pm',
    'map_embed' => 'https://maps.google.com/maps?q=Lucky%20Street%20Tajnagh%20Housing%20Scheme%20Lahore&t=&z=15&ie=UTF8&iwloc=&output=embed',
];

$nav = [
    ['label' => 'Home', 'href' => 'index.php', 'id' => 'home'],
    [
        'label' => 'Services',
        'href' => 'services.php',
        'id' => 'services',
        'children' => [
            ['General Dentistry', 'service-general.php'],
            ['Cosmetic Dentistry', 'service-cosmetic.php'],
            ['Orthodontics', 'service-orthodontics.php'],
            ['Pediatric Dentistry', 'service-pediatric.php'],
            ['Preventive Care', 'service-preventive.php'],
            ['Restorative Dentistry', 'service-restorative.php'],
        ],
    ],
    ['label' => 'Dentists', 'href' => 'dentists.php', 'id' => 'dentists'],
    [
        'label' => 'Pages',
        'href' => 'about.php',
        'id' => 'pages',
        'children' => [
            ['About', 'about.php'],
            ['Gallery', 'gallery.php'],
            ['FAQ', 'faq.php'],
            ['Reviews', 'testimonials.php'],
            ['Booking', 'booking.php'],
        ],
    ],
    ['label' => 'Blog', 'href' => 'blog.php', 'id' => 'blog'],
    ['label' => 'Contact', 'href' => 'contact.php', 'id' => 'contact'],
];

$services = [
    [
        'slug' => 'general',
        'title' => 'General Dentistry',
        'file' => 'service-general.php',
        'image' => 'assets/img/service-general.jpg',
        'icon' => 'tooth',
        'excerpt' => 'Exams, cleanings, and everyday care that keep your mouth healthy between visits.',
        'intro' => 'General dentistry is the foundation of a healthy smile. We combine gentle exams, digital diagnostics, and unhurried conversations so you always know what your teeth need — and what they do not.',
    ],
    [
        'slug' => 'cosmetic',
        'title' => 'Cosmetic Dentistry',
        'file' => 'service-cosmetic.php',
        'image' => 'assets/img/service-cosmetic.jpg',
        'icon' => 'sparkle',
        'excerpt' => 'Whitening, veneers, and smile design shaped around your features — never a template.',
        'intro' => 'Cosmetic work at Aurelia is quiet and considered. We refine shade, shape, and proportion so the result looks like you on your best day, not like a billboard smile.',
    ],
    [
        'slug' => 'orthodontics',
        'title' => 'Orthodontics',
        'file' => 'service-orthodontics.php',
        'image' => 'assets/img/service-ortho.jpg',
        'icon' => 'align',
        'excerpt' => 'Clear aligners and discreet braces for teens and adults who want a calmer path to alignment.',
        'intro' => 'Whether you prefer nearly invisible aligners or a traditional approach, we plan tooth movement with 3D imaging and check-ins that respect your calendar.',
    ],
    [
        'slug' => 'pediatric',
        'title' => 'Pediatric Dentistry',
        'file' => 'service-pediatric.php',
        'image' => 'assets/img/service-pediatric.jpg',
        'icon' => 'child',
        'excerpt' => 'First visits, sealants, and coaching that help children leave proud instead of anxious.',
        'intro' => 'Our kids’ studio is slower, brighter, and built for short attention spans. We celebrate small wins and never rush a first visit.',
    ],
    [
        'slug' => 'preventive',
        'title' => 'Preventive Care',
        'file' => 'service-preventive.php',
        'image' => 'assets/img/service-preventive.jpg',
        'icon' => 'shield',
        'excerpt' => 'Hygiene, fluoride, and habit coaching that stop problems before they need a drill.',
        'intro' => 'Prevention is the most generous dentistry we offer. We map risk, polish thoroughly, and send you home with a plan you can actually keep.',
    ],
    [
        'slug' => 'restorative',
        'title' => 'Restorative Dentistry',
        'file' => 'service-restorative.php',
        'image' => 'assets/img/service-restorative.jpg',
        'icon' => 'restore',
        'excerpt' => 'Crowns, implants, and bridges that restore comfort and strength without looking rebuilt.',
        'intro' => 'When a tooth is worn, cracked, or missing, we restore function first and aesthetics in the same conversation — using materials that last in real Portland weather and real life.',
    ],
];

$dentists = [
    [
        'name' => 'Dr. Maya Ellison',
        'role' => 'Lead Dentist & Founder',
        'image' => 'assets/img/dentist-1.jpg',
        'bio' => 'Maya founded Aurelia after a decade in hospital dentistry. She believes a calm operatory is as important as a precise filling.',
        'focus' => 'Smile design, implants',
        'education' => 'DDS, University of Washington',
    ],
    [
        'name' => 'Dr. Jonah Park',
        'role' => 'Orthodontist',
        'image' => 'assets/img/dentist-2.jpg',
        'bio' => 'Jonah plans alignment with 3D scans and a light touch. Teens and adults alike appreciate his clear timelines.',
        'focus' => 'Aligners, bite correction',
        'education' => 'DMD, Oregon Health & Science',
    ],
    [
        'name' => 'Dr. Priya Nair',
        'role' => 'Pediatric Dentist',
        'image' => 'assets/img/dentist-3.jpg',
        'bio' => 'Priya turns first visits into small adventures. Parents often say their children ask to come back.',
        'focus' => 'Children & teens',
        'education' => 'DDS, University of Michigan',
    ],
    [
        'name' => 'Dr. Elias Ward',
        'role' => 'Restorative Specialist',
        'image' => 'assets/img/dentist-4.jpg',
        'bio' => 'Elias rebuilds worn and damaged teeth so chewing feels ordinary again — the highest compliment in restorative work.',
        'focus' => 'Crowns, full-mouth rehab',
        'education' => 'DMD, Boston University',
    ],
];

$posts = [
    [
        'slug' => 'how-often-should-you-really-visit',
        'title' => 'How often should you really visit the dentist?',
        'date' => 'August 12, 2026',
        'author' => 'Dr. Maya Ellison',
        'image' => 'assets/img/blog-1.jpg',
        'excerpt' => 'Six months is a starting point, not a rule. Here is how we set recall based on gums, habits, and risk.',
        'file' => 'article.php?slug=how-often-should-you-really-visit',
    ],
    [
        'slug' => 'whitening-without-the-wince',
        'title' => 'Whitening without the wince',
        'date' => 'July 28, 2026',
        'author' => 'Dr. Jonah Park',
        'image' => 'assets/img/blog-2.jpg',
        'excerpt' => 'Sensitivity is the reason most people abandon trays. A slower protocol usually wins.',
        'file' => 'article.php?slug=whitening-without-the-wince',
    ],
    [
        'slug' => 'first-visit-for-a-nervous-child',
        'title' => 'A first visit for a nervous child',
        'date' => 'June 9, 2026',
        'author' => 'Dr. Priya Nair',
        'image' => 'assets/img/blog-3.jpg',
        'excerpt' => 'We never start with a drill. The goal of visit one is leaving proud — treatment can wait.',
        'file' => 'article.php?slug=first-visit-for-a-nervous-child',
    ],
];
